import type { JobApplication } from "./types/application";

export const applications: JobApplication[] = [
  {
    id: 1,
    company: "Google",
    position: "Frontend Developer Intern",
    location: "Remote",
    status: "applied",
    jobType: "internship",
    dateApplied: "2026-09-15",
    deadline: "2026-09-25",
    note: "Applied through the careers page.",
  },
  {
    id: 2,
    company: "Microsoft",
    position: "Software Engineering Intern",
    location: "Addis Ababa",
    status: "interviewed",
    jobType: "internship",
    dateApplied: "2026-09-12",
    note: "Technical interview completed. Waiting for feedback.",
  },
  {
    id: 3,
    company: "Safaricom Ethiopia",
    position: "Junior Frontend Developer",
    location: "Addis Ababa",
    status: "offered",
    jobType: "full-time",
    dateApplied: "2026-09-08",
    deadline: "2026-09-22",
    note: "Offer received. Need to respond before the deadline.",
  },
  {
    id: 4,
    company: "Ethiopian Airlines",
    position: "Software Developer",
    location: "Addis Ababa",
    status: "rejected",
    jobType: "full-time",
    dateApplied: "2026-09-05",
  },
  {
    id: 5,
    company: "Chapa",
    position: "Frontend Developer Intern",
    location: "Addis Ababa",
    status: "saved",
    jobType: "internship",
    dateApplied: "2026-09-16",
    deadline: "2026-09-30",
    note: "Review the requirements before applying.",
  },
  {
    id: 6,
    company: "Flutterwave",
    position: "React Developer",
    location: "Remote",
    status: "applied",
    jobType: "full-time",
    dateApplied: "2026-09-14",
    note: "Application submitted with updated React projects.",
  },
  {
    id: 7,
    company: "Andela",
    position: "Junior Software Engineer",
    location: "Remote",
    status: "interviewed",
    jobType: "full-time",
    dateApplied: "2026-09-10",
    deadline: "2026-09-20",
    note: "Second interview scheduled.",
  },
  {
    id: 8,
    company: "A2SV",
    position: "Software Engineering Trainee",
    location: "Addis Ababa",
    status: "applied",
    jobType: "internship",
    dateApplied: "2026-09-11",
    deadline: "2026-09-28",
  },
  {
    id: 9,
    company: "iCog Labs",
    position: "AI Software Engineer Intern",
    location: "Addis Ababa",
    status: "saved",
    jobType: "internship",
    dateApplied: "2026-09-13",
    deadline: "2026-10-01",
    note: "Need to prepare an AI-related project for the application.",
  },
  {
    id: 10,
    company: "GitLab",
    position: "Frontend Engineer",
    location: "Remote",
    status: "rejected",
    jobType: "full-time",
    dateApplied: "2026-08-29",
    note: "Rejected after initial application review.",
  },
];
